title: Nonprofit Open Science Toolkit
author: lecy
email: jdlecy@asu.edu
description: An introduction to the data science ecosystem for <br>nonprofit scholarship

github_username:  lecy

sass:
    style: compressed
