title: Nonprofit Open Science Toolkit
author: lecy
email: jdlecy@asu.edu
description: An introduction to the data science ecosystem for nonprofit scholarship

github_username:  lecy

sass:
    style: compressed
